version: build_number_{build}
configuration: Release
skip_tags: true
init:
- ps: "$v = [regex]::match($env:APPVEYOR_REPO_BRANCH,'release/(.*)').Groups[1].Value\nWrite-Host \"On branch $($env:APPVEYOR_REPO_BRANCH)\"\nIF($v) { \n   $env:VERSION_FROM_BRANCH = \"$($v).$($env:APPVEYOR_BUILD_NUMBER)\"\n} else {\n   $env:VERSION_FROM_BRANCH = \"0.0.0.$($env:APPVEYOR_BUILD_NUMBER)\"\n}\nWrite-Host \"Set version to $($env:VERSION_FROM_BRANCH)\""
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VERSION_FROM_BRANCH)
  assembly_file_version: $(VERSION_FROM_BRANCH)
  assembly_informational_version: $(VERSION_FROM_BRANCH)
environment:
  COVERALLS_REPO_TOKEN:
    secure: qjY74qfU6R9CZnQA3JyIf9d/WxZBuVF2ysEapYlNnoUW2L7uMgsVDwmOWMHekof2
build:
  parallel: true
  verbosity: normal
test_script:
- cmd:
    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -register:user "-targetargs:""src\PostalCodes.UnitTests\bin\Release\PostalCodes.UnitTests.dll"" /noshadow" -filter:"+[PostalCodes*]*" -output:opencoverCoverage.xml

    IF "%COVERALLS_REPO_TOKEN%"=="" (exit 0) else (.\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken "%COVERALLS_REPO_TOKEN%" --commitId "%APPVEYOR_REPO_COMMIT%" --commitBranch "%APPVEYOR_REPO_BRANCH%" --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId "%APPVEYOR_JOB_ID%")

artifacts:
- path: src\PostalCodes\bin\*\*.nupkg
  name: NuGet
- path: src\PostalCodes\bin\*\*.dll
  name: Dlls
- path: src\PostalCodes.Documentation\Help\*.chm
  name: Documentation
deploy:
- provider: NuGet
  api_key:
    secure: DK9YLl9zwAwoGGPvu+Sf25PN9lLuiIUJgJ/hXXfJiTUNr5FVSIDuio5/Ncl2suLY
  skip_symbols: true
  artifact: NuGet
  on:
    branch: /release/.*/
- provider: GitHub
  release: $(VERSION_FROM_BRANCH)
  auth_token:
    secure: WU3IlQqOmPsEQ5Gsmj9MMBMdwNynLhxuBBK5C1SiPBygO78NcehvQw92TOfDkEq0
  artifact: Dlls, Documentation
  on:
    branch: /release/.*/
notifications:
- provider: HipChat
  room: MSW Logistics Quoting and Planning
  auth_token:
    secure: Bom1JR9YuKXK/fN7SW+R0LMb6KqYZEo2dJDnuoMxdfU=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
